apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc
  namespace: default
  labels:
    app: jenkins
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: standard-rwo  # Cheaper than SSD
  resources:
    requests:
      storage: 10Gi  # Smaller size to reduce costs