apiVersion: apps/v1
kind: Deployment
metadata:
  name: jenkins
  namespace: default
  labels:
    app: jenkins
spec:
  replicas: 1
  # Use RollingUpdate for zero-downtime updates
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      securityContext:
        runAsUser: 1000
        runAsGroup: 1000
        fsGroup: 1000
      containers:
        - name: jenkins
          image: gcr.io/jenkins-cicd-dashboard/jenkins-dind:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: jnlp
              containerPort: 50000
              protocol: TCP
          env:
            # Set the JAVA_OPTS to align with the container limits
            - name: JAVA_OPTS
              value: "-Xmx512m -Xms256m"
          resources:
            requests:
              # Ensure resource requests are realistic and match the JVM settings
              memory: "512Mi"
              cpu: "100m"
            limits:
              # Set a reasonable upper bound for memory to prevent OOMKills
              memory: "768Mi"
              cpu: "500m"
          volumeMounts:
            - name: jenkins-volume
              mountPath: /var/jenkins_home
          livenessProbe:
            httpGet:
              path: /login
              port: 8080
            # Increase initial delay to give Jenkins more time to start up
            initialDelaySeconds: 240
            periodSeconds: 30
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /login
              port: 8080
            # Increase initial delay to give Jenkins more time to become ready
            initialDelaySeconds: 180
            periodSeconds: 10
            timeoutSeconds: 5
      volumes:
        - name: jenkins-volume
          persistentVolumeClaim:
            claimName: jenkins-pvc
